### ISSUE TITLE
Error timeline @__________: response status 404 Not Found

### ISSUE THREAD

**Issue by rtega** [n0madic/twitter2rss#8]
Since a few days we get this response. Doesn't seem to work anymore.

**Comment by n0madic** [comment]
https://twitter.com/elonmusk/status/1675187969420828672

> To address extreme levels of data scraping & system manipulation, we’ve applied the following temporary limits:
> 
> - Verified accounts are limited to reading 6000 posts/day
> - Unverified accounts to 600 posts/day
> - New unverified accounts to 300/day

**Comment by CaptainFlint** [comment]
If it were caused by this new restrictions, it would allow reading up to 300 tweets at the start of a new day. And my self-hosted version of twitter2rss keeps getting 404 since June 30, without any single successful response. It looks to me, like in addition to those restrictions, some page addresses have been changed, which twitter2rss relied on.

**Comment by rtega** [comment]
Exactly what I was thinking.

**Comment by rtega** [comment]
Since a few hours it seems to be working again.
